import { Decision } from "./types";

export const mockDecisions: Decision[] = [
  {
    id: "DEC-001",
    workerName: "Customer Support AI",
    action: "Refund Approval",
    riskLevel: "Low",
    confidence: 97,
    status: "Approved",
    createdAt: "10 mins ago",
    policy: "Refund Policy v2",
    details: "Approved refund of $45.00 for order #8829",
    reason: "Customer requested refund within 30-day window. Item condition marked as 'unopened'.",
  },
  {
    id: "DEC-002",
    workerName: "Sales Outreach Agent",
    action: "Discount Override",
    riskLevel: "Medium",
    confidence: 82,
    status: "Pending",
    createdAt: "1 hour ago",
    policy: "Discount Limits",
    details: "Requested 25% discount for enterprise prospect",
    reason: "Competitor pricing matching required to close deal. Exceeds standard 15% auto-approval limit.",
  },
  {
    id: "DEC-003",
    workerName: "Infrastructure Auto-Scaler",
    action: "Cluster Scale Up",
    riskLevel: "High",
    confidence: 99,
    status: "Approved",
    createdAt: "3 hours ago",
    policy: "Production Access",
    details: "Scaled up production EKS cluster by 20 nodes",
    reason: "CPU utilization exceeded 85% sustained over 5 minutes. Anticipating traffic spike.",
  },
  {
    id: "DEC-004",
    workerName: "HR Screening Bot",
    action: "Candidate Rejection",
    riskLevel: "Low",
    confidence: 88,
    status: "Rejected",
    createdAt: "5 hours ago",
    policy: "Fair Hiring Act",
    details: "Auto-rejected application for Senior Engineer",
    reason: "Missing mandatory 5+ years experience requirement.",
  },
  {
    id: "DEC-005",
    workerName: "Finance Bot",
    action: "Invoice Payment",
    riskLevel: "High",
    confidence: 75,
    status: "Escalated",
    createdAt: "1 day ago",
    policy: "Vendor Payments",
    details: "Initiated $50,000 wire transfer to new vendor",
    reason: "First-time payment to this vendor. Confidence score below 80% threshold for high-value transfers.",
  },
];