"""dynamic policy engine v2

Revision ID: c9237327705c
Revises: adf9a04a6f69
Create Date: 2026-05-29 03:40:18.913340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9237327705c'
down_revision: Union[str, Sequence[str], None] = 'adf9a04a6f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    existing = {
        row[0]
        for row in conn.execute(
            sa.text(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = 'policies'
                """
            )
        )
    }

    if 'agent' not in existing:
        op.add_column('policies', sa.Column('agent', sa.String(), nullable=True))

    if 'action' not in existing:
        op.add_column('policies', sa.Column('action', sa.String(), nullable=True))

    if 'resource' not in existing:
        op.add_column('policies', sa.Column('resource', sa.String(), nullable=True))

    if 'condition' not in existing:
        op.add_column('policies', sa.Column('condition', sa.String(), nullable=True))

    if 'effect' not in existing:
        op.add_column('policies', sa.Column('effect', sa.String(), nullable=True))

    if 'risk_level' not in existing:
        op.add_column('policies', sa.Column('risk_level', sa.String(), nullable=True))

    if 'action_type' in existing:
        op.drop_column('policies', 'action_type')

    if 'needs_approval' in existing:
        op.drop_column('policies', 'needs_approval')

    if 'max_amount' in existing:
        op.drop_column('policies', 'max_amount')

    if 'agent_id' in existing:
        try:
            op.drop_constraint(op.f('policies_agent_id_fkey'), 'policies', type_='foreignkey')
        except Exception:
            pass
        op.drop_column('policies', 'agent_id')

    if 'environment' in existing:
        op.drop_column('policies', 'environment')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('environment', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('policies', sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('policies', sa.Column('max_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('policies', sa.Column('needs_approval', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('policies', sa.Column('action_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('policies_agent_id_fkey'), 'policies', 'agents', ['agent_id'], ['id'])
    op.drop_column('policies', 'risk_level')
    op.drop_column('policies', 'effect')
    op.drop_column('policies', 'condition')
    op.drop_column('policies', 'resource')
    op.drop_column('policies', 'action')
    op.drop_column('policies', 'agent')
    # ### end Alembic commands ###
