import { Agent } from './types';

export const mockWorkers: Agent[] = [
  {
    id: 'wk-001',
    name: 'Customer Support Bot',
    description: 'Handles tier 1 customer inquiries and refund requests.',
    department: 'Support',
    status: 'Active',
    riskLevel: 'Low',
    decisionsToday: 1245,
    successRate: 98.5,
    lastActivity: '2023-10-25T10:23:00Z',
    assignedPolicies: ['Data Privacy V2', 'Refund Limits'],
    approvalRequirements: 'Refunds > $50 require human approval',
  },
  {
    id: 'wk-002',
    name: 'Sales Outreach Agent',
    description: 'Automates email outreach and meeting scheduling.',
    department: 'Sales',
    status: 'Paused',
    riskLevel: 'Medium',
    decisionsToday: 0,
    successRate: 85.2,
    lastActivity: '2023-10-24T15:45:00Z',
    assignedPolicies: ['Email Communication', 'CAN-SPAM Compliance'],
    approvalRequirements: 'New campaign templates require approval',
  },
  {
    id: 'wk-003',
    name: 'Infrastructure Auto-Scaler',
    description: 'Monitors load and scales Kubernetes clusters.',
    department: 'Engineering',
    status: 'Active',
    riskLevel: 'High',
    decisionsToday: 42,
    successRate: 99.9,
    lastActivity: '2023-10-25T10:30:00Z',
    assignedPolicies: ['Production Access', 'Cost Control'],
    approvalRequirements: 'Scaling > 50 nodes requires approval',
  },
  {
    id: 'wk-004',
    name: 'HR Screening Bot',
    description: 'Screens initial resumes and matches keywords.',
    department: 'HR',
    status: 'Maintenance',
    riskLevel: 'Low',
    decisionsToday: 18,
    successRate: 92.0,
    lastActivity: '2023-10-25T08:15:00Z',
    assignedPolicies: ['Fair Hiring Act', 'PII Masking'],
    approvalRequirements: 'Rejection of candidates requires approval',
  },
];